#!/usr/bin/php
<?php

use ImageViewer\Commands\ThumbnailsCommand;
use ImageViewer\Commands\ThumbnailsWorkerCommand;
use ImageViewer\Commands\UpdateFilesystemCommand;
use ImageViewer\Commands\UpdateJsonCacheCommand;
use ImageViewer\Commands\UpdateMetadataCommand;
use ImageViewer\Commands\UpdateStructureCommand;
use ImageViewer\Configuration\Configuration;
use ImageViewer\Factory;
use Symfony\Component\Console\Application;

require __DIR__ . '/../vendor/autoload.php';

try {

    $config = new Configuration(__dir__ . '/../../config/local.ini');
    $factory = new Factory($config);

    $application = new Application();
    $application->add(new UpdateFilesystemCommand($factory));
    $application->add(new UpdateStructureCommand($factory));
    $application->add(new UpdateMetadataCommand($factory));
    $application->add(new ThumbnailsCommand($factory));
    $application->add(new ThumbnailsWorkerCommand($factory));
    $application->add(new UpdateJsonCacheCommand($factory));
    $application->run();

} catch (Exception $e) {
    echo $e->getMessage();
}


