name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
        extensions: mbstring, xml, pcntl, exif, json, pdo, gd
        ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
        coverage: xdebug #optional, setup coverage driver
        tools: php-cs-fixer, phpunit

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Run tests
      run: |
        make test_unit
